version: "3"
services:
  hapi-fhir:
    build: .
    container_name: hapi-fhir
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      hapi:
  hapi-postgres:
    image: postgres:9-alpine
    container_name: hapi-postgres
    restart: unless-stopped
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
    ports:
      - "7766:5432"
    networks:
      hapi:
volumes:
  hapi-postgres:
networks:
  hapi:
